name: Nix

on:
  push:
    branches:
      - main
      - release-*
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24

      - uses: Swatinem/rust-cache@v2

      - name: Nix environment loads
        run: nix develop -c echo Success

      - name: Nix environment builds all targets
        run: nix develop -c cargo build --all-targets --all-features --release --workspace

      - name: Precommit hooks work
        run: nix develop -c pre-commit run --all-files
